### ISSUE TITLE
StateFlow of a Kotlin collection renders as <rootPackage>.Kotlin.Collections.List and drops the type argument

### ISSUE THREAD

**Issue by xxfast** [xxfast/kotlin-native-nuget#127]
A `StateFlow` whose element type is a Kotlin collection renders the collection as `<rootPackage>.Kotlin.Collections.List`, with `rootPackage` prefixed onto `kotlin.collections` and the type argument dropped. That namespace does not exist, so `Interop.cs` does not compile.

Same family as #122, third route. `rootPackage = "com.example.demo"` here, mapping to `Demo`.

```kotlin
class Hub {
  val items: StateFlow<Set<NodeId>> = MutableStateFlow(emptySet())

  fun visible(kinds: List<Kind>): StateFlow<List<NodeId>> = MutableStateFlow(emptyList())
}
```

```csharp
// wrong, both the flow property and the flow-returning method
public KotlinStateFlow<global::Demo.Kotlin.Collections.Set> Items { get; }
public KotlinStateFlow<global::Demo.Kotlin.Collections.List> Visible(IReadOnlyList<global::Demo.Kind> kinds)
```

```
Interop.cs(1176,62): error CS0234: The type or namespace name 'Kotlin' does not exist in the namespace 'Demo.Kotlin'
Interop.cs(1258,62): error CS0234: The type or namespace name 'Kotlin' does not exist in the namespace 'Demo.Kotlin'
```

Two things are wrong and they may be one bug or two. `kotlin.collections.List` is being treated as a user type and run through the `rootPackage` mapping instead of being recognised as a builtin, and the type argument is dropped on the way.

## What is already correct, so the shape of the gap is visible

Note the second example: **the parameter in that same signature is right.** `List<Kind>` renders as `IReadOnlyList<global::Demo.Kind>` while the return renders as `global::Demo.Kotlin.Collections.List`. Same declaration, same Kotlin type constructor, one position right and one wrong.

The plain property route is right too, and #124 just fixed the suspend-return route to `Task<IReadOnlyList<T>>`. So `IReadOnlyList<T>` is the settled contract for a Kotlin `List<T>` in three routes already, and the `nuget_list_create` / `_add` / `_count` / `_get` helpers this needs are emitted and in use.

## Requirements

1. `StateFlow<List<T>>` renders as `KotlinStateFlow<IReadOnlyList<T>>`, and `StateFlow<Set<T>>` as `KotlinStateFlow<IReadOnlySet<T>>`, with `T` spelled exactly as the parameter route on the same declaration spells it, fully qualified.
2. Same for a `Flow` and for a flow-returning method, not just a property.
3. It marshals through the existing `nuget_list_*` helpers, so the routes agree at runtime and not only in the signature.
4. No emitted C# type name contains `rootPackage` followed by a `kotlin.*` package segment. A Kotlin builtin should never be mapped as a user type.
5. If (1) is out of scope for this route, **skip the member with a named `SKIPPED_*` diagnostic instead**. A member that is absent and says why is acceptable; one that is present and references a namespace that does not exist is not.

Please do not fix it by spelling the element as `object`, `IntPtr` or a non-generic `IEnumerable`. Three routes already use `IReadOnlyList<T>` for a Kotlin `List<T>`, and a fourth spelling for the same Kotlin type would be worse than the current error.

## Scope

Verified for `StateFlow<Set<T>>` on a property and `StateFlow<List<T>>` on a method return, where `T` is a value class. Not checked: `Flow` rather than `StateFlow`, `Map<K, V>`, a nested collection, or a collection of a sealed type. The `rootPackage` mapping bug in (4) is likely wider than flows and worth grepping for on its own.

## Verified against a real project

`packNuget` is green with this in it. The failure only shows when the generated `Interop.cs` is compiled separately.

**Comment by xxfast** [comment]
Reopening, for the same reason as #126 and with the same root cause: this is fixed when the owning class is admitted from a dependency klib, and still broken when it is module-local source. Verified on released `0.6.0`.

## The two routes, same declaration

```kotlin
class Hub {
  val known: StateFlow<Set<Saved>>
  fun nearby(kinds: List<Kind>): StateFlow<List<Nearby>>
  suspend fun forget(ids: Set<Id>)
}
```

Plugin applied to a **wrapper module** that depends on the module declaring `Hub`:

```csharp
public KotlinStateFlow<IReadOnlySet<global::Demo.Saved>> Known                                  // correct
public KotlinStateFlow<IReadOnlyList<global::Demo.Nearby>> Nearby(IReadOnlyList<global::Demo.Kind> kinds)  // correct
public Task ForgetAsync(IReadOnlySet<global::Demo.Id> ids, CancellationToken cancellationToken = default)  // correct
```

Plugin applied to the **module that declares `Hub` itself**:

```csharp
public KotlinStateFlow<global::Demo.Kotlin.Collections.Set> Known
public KotlinStateFlow<global::Demo.Kotlin.Collections.List> Nearby(IReadOnlyList<global::Demo.Kind> kinds)
public Task ForgetAsync(IReadOnlySet<global::Demo.Id> ids, CancellationToken cancellationToken = default)  // still correct
```

```
Interop.cs(1158,62): error CS0234: The type or namespace name 'Kotlin' does not exist in the namespace 'Demo'
Interop.cs(1240,62): error CS0234: The type or namespace name 'Kotlin' does not exist in the namespace 'Demo'
```

Exactly the original symptom: `<rootPackage>.Kotlin.Collections.Set` / `.List`, a namespace that does not exist, with the type argument dropped.

## What this narrows it to

`ForgetAsync` is the useful control. A plain `Set<Id>` in a **parameter** position maps to `IReadOnlySet<Id>` correctly on **both** routes. So collection mapping is not broken in general on the module-local route. It is specifically a collection nested inside `StateFlow<...>` in a return or property position that loses its mapping, and only when the owner is local source.

Both failures are in the same shape (`Flow`-wrapped collection, return position), and both work when the owner arrives from a klib. The `nearby(kinds: List<Kind>)` line is the clearest single case: its **parameter** `IReadOnlyList<Kind>` is right and its **return** `StateFlow<List<Nearby>>` is wrong, in one signature, in one run.

Confirmed the same way as #126: `Hub` appears in the wrapper module's `INFO_EXPORTED_FROM_DEPENDENCY` list and not in the declaring module's. Nothing else differs between the runs.

## Requirements

Everything in the original issue, plus:

1. `StateFlow<Set<T>>` and `StateFlow<List<T>>` in a return or property position render as `KotlinStateFlow<IReadOnlySet<T>>` / `KotlinStateFlow<IReadOnlyList<T>>` when the owning class is module-local source, identically to the dependency-admitted case.
2. The two routes agree, character for character, for the same Kotlin declarations. A fixture pair asserting that is worth more than either case alone.
3. `nearby(kinds: List<Kind>): StateFlow<List<Nearby>>` is a good single regression fixture, since parameter and return exercise both directions of the same mapping in one declaration.

## Please do not fix it these ways

- **Do not emit `<rootPackage>.Kotlin.Collections.Set` as a real namespace** to make it resolve. The type argument is also gone, so the result would compile and still be unusable.
- **Do not fix the property route and leave the function-return route**, or vice versa. `known` is a property and `nearby` is a function return, and both are broken here.

**Comment by xxfast** [comment]
Closing again, same reason as #126: the fix isn't in `0.6.0`.

`0.6.0` is tagged at `711c797b` (2026-09-09). ADR-123 landed in `af3c8628` on 2026-09-10. At the tag, `qualifiedElementCsType` misses `Set`/`List` in the primitive table, takes the bare nested name (argument dropped) and runs `kotlin.collections` through `mapPackageToNamespace`, which is exactly `global::Demo.Kotlin.Collections.Set`. `main` now also has a `check` in `CirTypeMapping.kt` that throws before that namespace can ever be emitted.

Owner provenance isn't an input here either: the flow element route keys on the return type only. Reproduced on `main` with `Hub` local and `Hub` from a dependency jar, `T` local and `T` from a dependency: all emit `KotlinStateFlow<IReadOnlySet<global::Interop.Saved>> Known` and `KotlinStateFlow<IReadOnlyList<global::Interop.Nearby>> Nearby(IReadOnlyList<global::Interop.Kind> kinds)`, character for character.

So the wrapper-module run was a `main` build and the declaring-module run was the released artifact. Re-run the declaring module against the same local version. If it still reproduces, reopen with the resolved plugin version.

Same note as #126: `issue127/Issue127Sample.kt` only covers the module-local route; a two-route fixture pair is worth adding separately.
